import { ReplayRecord, URLS } from '../constants';

const STANDARD_PLAYER_AVATAR = 'standard-avatar.png';

const defaultReplaysDB: Array<ReplayRecord> = [
  {
    firstPlayer: {
      name: 'Anatoly Karpov',
      chessmanColor: 'white',
      status: 'Surrender',
      avatarUrl: `${URLS.iconsPath}/${STANDARD_PLAYER_AVATAR}`,
    },
    secondPlayer: {
      name: 'Garry Kasparov',
      chessmanColor: 'black',
      status: 'Win',
      avatarUrl: `${URLS.iconsPath}/${STANDARD_PLAYER_AVATAR}`,
    },
    totalTime: 'unknown',
    log: [
      'white-pawn: E2-E4',
      'black-pawn: C7-C5',
      'white-knight: G1-F3',
      'black-pawn: E7-E6',
      'white-pawn: D2-D4',
      'black-pawn: C5-D4',
      'white-knight: F3-D4',
      'black-knight: B8-C6',
      'white-knight: D4-B5',
      'black-pawn: D7-D6',
      'white-pawn: C2-C4',
      'black-knight: G8-F6',
      'white-knight: B1-C3',
      'black-pawn: A7-A6',
      'white-knight: B5-A3',
      'black-pawn: D6-D5',
      'white-pawn: C4-D5',
      'black-pawn: E6-D5',
      'white-pawn: E4-D5',
      'black-knight: C6-B4',
      'white-bishop: F1-E2',
      'black-bishop: F8-C5',
      'white-king: E1-G1+white-rook: H1-F1',
      'black-king: E8-G8+black-rook: H8-F8',
      'white-bishop: E2-F3',
      'black-bishop: C8-F5',
      'white-bishop: C1-G5',
      'black-rook: F8-E8',
      'white-queen: D1-D2',
      'black-pawn: B7-B5',
      'white-rook: A1-D1',
      'black-knight: B4-D3',
      'white-knight: A3-B1',
      'black-pawn: H7-H6',
      'white-bishop: G5-H4',
      'black-pawn: B5-B4',
      'white-knight: C3-A4',
      'black-bishop: C5-D6',
      'white-bishop: H4-G3',
      'black-rook: A8-C8',
      'white-pawn: B2-B3',
      'black-pawn: G7-G5',
      'white-bishop: G3-D6',
      'black-queen: D8-D6',
      'white-pawn: G2-G3',
      'black-knight: F6-D7',
      'white-bishop: F3-G2',
      'black-queen: D6-F6',
      'white-pawn: A2-A3',
      'black-pawn: A6-A5',
      'white-pawn: A3-B4',
      'black-pawn: A5-B4',
      'white-queen: D2-A2',
      'black-bishop: F5-G6',
      'white-pawn: D5-D6',
      'black-pawn: G5-G4',
      'white-queen: A2-D2',
      'black-king: G8-G7',
      'white-pawn: F2-F3',
      'black-queen: F6-D6',
      'white-pawn: F3-G4',
      'black-queen: D6-D4',
      'white-king: G1-H1',
      'black-knight: D7-F6',
      'white-rook: F1-F4',
      'black-knight: F6-E4',
      'white-queen: D2-D3',
      'black-knight: E4-F2',
      'white-rook: F4-F2',
      'black-bishop: G6-D3',
      'white-rook: F2-D2',
      'black-queen: D4-E3',
      'white-rook: D2-D3',
      'black-rook: C8-C1',
      'white-knight: A4-B2',
      'black-queen: E3-F2',
      'white-knight: B1-D2',
      'black-rook: C1-D1',
      'white-knight: B2-D1',
      'black-rook: E8-E1',
    ],
    title: `Anatoly Karpov surrendered!
      Garry Kasparov wins the game.`,
  },
];

export default defaultReplaysDB;
